// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.12.4
// source: agents.proto

package patronobuf

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RequestType int32

const (
	RequestType_CONFIGURATION  RequestType = 0
	RequestType_COMMAND        RequestType = 1
	RequestType_COMMAND_STATUS RequestType = 2
	RequestType_KEYS           RequestType = 3
	RequestType_FILE           RequestType = 4
	RequestType_FILE_TO_SERVER RequestType = 5
)

// Enum value maps for RequestType.
var (
	RequestType_name = map[int32]string{
		0: "CONFIGURATION",
		1: "COMMAND",
		2: "COMMAND_STATUS",
		3: "KEYS",
		4: "FILE",
		5: "FILE_TO_SERVER",
	}
	RequestType_value = map[string]int32{
		"CONFIGURATION":  0,
		"COMMAND":        1,
		"COMMAND_STATUS": 2,
		"KEYS":           3,
		"FILE":           4,
		"FILE_TO_SERVER": 5,
	}
)

func (x RequestType) Enum() *RequestType {
	p := new(RequestType)
	*p = x
	return p
}

func (x RequestType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RequestType) Descriptor() protoreflect.EnumDescriptor {
	return file_agents_proto_enumTypes[0].Descriptor()
}

func (RequestType) Type() protoreflect.EnumType {
	return &file_agents_proto_enumTypes[0]
}

func (x RequestType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RequestType.Descriptor instead.
func (RequestType) EnumDescriptor() ([]byte, []int) {
	return file_agents_proto_rawDescGZIP(), []int{0}
}

type ResponseType int32

const (
	ResponseType_CONFIGURATION_RESPONSE  ResponseType = 0
	ResponseType_COMMAND_RESPONSE        ResponseType = 1
	ResponseType_COMMAND_STATUS_RESPONSE ResponseType = 2
	ResponseType_KEYS_RESPONSE           ResponseType = 3
	ResponseType_FILE_RESPONSE           ResponseType = 4
	ResponseType_FILE_TRANSFER_STATUS    ResponseType = 5
)

// Enum value maps for ResponseType.
var (
	ResponseType_name = map[int32]string{
		0: "CONFIGURATION_RESPONSE",
		1: "COMMAND_RESPONSE",
		2: "COMMAND_STATUS_RESPONSE",
		3: "KEYS_RESPONSE",
		4: "FILE_RESPONSE",
		5: "FILE_TRANSFER_STATUS",
	}
	ResponseType_value = map[string]int32{
		"CONFIGURATION_RESPONSE":  0,
		"COMMAND_RESPONSE":        1,
		"COMMAND_STATUS_RESPONSE": 2,
		"KEYS_RESPONSE":           3,
		"FILE_RESPONSE":           4,
		"FILE_TRANSFER_STATUS":    5,
	}
)

func (x ResponseType) Enum() *ResponseType {
	p := new(ResponseType)
	*p = x
	return p
}

func (x ResponseType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ResponseType) Descriptor() protoreflect.EnumDescriptor {
	return file_agents_proto_enumTypes[1].Descriptor()
}

func (ResponseType) Type() protoreflect.EnumType {
	return &file_agents_proto_enumTypes[1]
}

func (x ResponseType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ResponseType.Descriptor instead.
func (ResponseType) EnumDescriptor() ([]byte, []int) {
	return file_agents_proto_rawDescGZIP(), []int{1}
}

type Request struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Type  RequestType            `protobuf:"varint,1,opt,name=type,proto3,enum=patronobuf.RequestType" json:"type,omitempty"`
	// Types that are valid to be assigned to Payload:
	//
	//	*Request_Configuration
	//	*Request_Command
	//	*Request_CommandStatus
	//	*Request_Keys
	//	*Request_File
	//	*Request_FileToServer
	Payload       isRequest_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Request) Reset() {
	*x = Request{}
	mi := &file_agents_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Request) ProtoMessage() {}

func (x *Request) ProtoReflect() protoreflect.Message {
	mi := &file_agents_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Request.ProtoReflect.Descriptor instead.
func (*Request) Descriptor() ([]byte, []int) {
	return file_agents_proto_rawDescGZIP(), []int{0}
}

func (x *Request) GetType() RequestType {
	if x != nil {
		return x.Type
	}
	return RequestType_CONFIGURATION
}

func (x *Request) GetPayload() isRequest_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *Request) GetConfiguration() *ConfigurationRequest {
	if x != nil {
		if x, ok := x.Payload.(*Request_Configuration); ok {
			return x.Configuration
		}
	}
	return nil
}

func (x *Request) GetCommand() *CommandRequest {
	if x != nil {
		if x, ok := x.Payload.(*Request_Command); ok {
			return x.Command
		}
	}
	return nil
}

func (x *Request) GetCommandStatus() *CommandStatusRequest {
	if x != nil {
		if x, ok := x.Payload.(*Request_CommandStatus); ok {
			return x.CommandStatus
		}
	}
	return nil
}

func (x *Request) GetKeys() *KeysRequest {
	if x != nil {
		if x, ok := x.Payload.(*Request_Keys); ok {
			return x.Keys
		}
	}
	return nil
}

func (x *Request) GetFile() *FileRequest {
	if x != nil {
		if x, ok := x.Payload.(*Request_File); ok {
			return x.File
		}
	}
	return nil
}

func (x *Request) GetFileToServer() *FileToServer {
	if x != nil {
		if x, ok := x.Payload.(*Request_FileToServer); ok {
			return x.FileToServer
		}
	}
	return nil
}

type isRequest_Payload interface {
	isRequest_Payload()
}

type Request_Configuration struct {
	Configuration *ConfigurationRequest `protobuf:"bytes,2,opt,name=configuration,proto3,oneof"`
}

type Request_Command struct {
	Command *CommandRequest `protobuf:"bytes,3,opt,name=command,proto3,oneof"`
}

type Request_CommandStatus struct {
	CommandStatus *CommandStatusRequest `protobuf:"bytes,4,opt,name=command_status,json=commandStatus,proto3,oneof"`
}

type Request_Keys struct {
	Keys *KeysRequest `protobuf:"bytes,5,opt,name=keys,proto3,oneof"`
}

type Request_File struct {
	File *FileRequest `protobuf:"bytes,6,opt,name=file,proto3,oneof"`
}

type Request_FileToServer struct {
	FileToServer *FileToServer `protobuf:"bytes,7,opt,name=file_to_server,json=fileToServer,proto3,oneof"`
}

func (*Request_Configuration) isRequest_Payload() {}

func (*Request_Command) isRequest_Payload() {}

func (*Request_CommandStatus) isRequest_Payload() {}

func (*Request_Keys) isRequest_Payload() {}

func (*Request_File) isRequest_Payload() {}

func (*Request_FileToServer) isRequest_Payload() {}

type Response struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Type  ResponseType           `protobuf:"varint,1,opt,name=type,proto3,enum=patronobuf.ResponseType" json:"type,omitempty"`
	// Types that are valid to be assigned to Payload:
	//
	//	*Response_ConfigurationResponse
	//	*Response_CommandResponse
	//	*Response_CommandStatusResponse
	//	*Response_KeysResponse
	//	*Response_FileResponse
	//	*Response_FileTransferStatusResponse
	Payload       isResponse_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Response) Reset() {
	*x = Response{}
	mi := &file_agents_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Response) ProtoMessage() {}

func (x *Response) ProtoReflect() protoreflect.Message {
	mi := &file_agents_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Response.ProtoReflect.Descriptor instead.
func (*Response) Descriptor() ([]byte, []int) {
	return file_agents_proto_rawDescGZIP(), []int{1}
}

func (x *Response) GetType() ResponseType {
	if x != nil {
		return x.Type
	}
	return ResponseType_CONFIGURATION_RESPONSE
}

func (x *Response) GetPayload() isResponse_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *Response) GetConfigurationResponse() *ConfigurationResponse {
	if x != nil {
		if x, ok := x.Payload.(*Response_ConfigurationResponse); ok {
			return x.ConfigurationResponse
		}
	}
	return nil
}

func (x *Response) GetCommandResponse() *CommandResponse {
	if x != nil {
		if x, ok := x.Payload.(*Response_CommandResponse); ok {
			return x.CommandResponse
		}
	}
	return nil
}

func (x *Response) GetCommandStatusResponse() *CommandStatusResponse {
	if x != nil {
		if x, ok := x.Payload.(*Response_CommandStatusResponse); ok {
			return x.CommandStatusResponse
		}
	}
	return nil
}

func (x *Response) GetKeysResponse() *KeysResponse {
	if x != nil {
		if x, ok := x.Payload.(*Response_KeysResponse); ok {
			return x.KeysResponse
		}
	}
	return nil
}

func (x *Response) GetFileResponse() *FileResponse {
	if x != nil {
		if x, ok := x.Payload.(*Response_FileResponse); ok {
			return x.FileResponse
		}
	}
	return nil
}

func (x *Response) GetFileTransferStatusResponse() *FileTransferStatusResponse {
	if x != nil {
		if x, ok := x.Payload.(*Response_FileTransferStatusResponse); ok {
			return x.FileTransferStatusResponse
		}
	}
	return nil
}

type isResponse_Payload interface {
	isResponse_Payload()
}

type Response_ConfigurationResponse struct {
	ConfigurationResponse *ConfigurationResponse `protobuf:"bytes,2,opt,name=configuration_response,json=configurationResponse,proto3,oneof"`
}

type Response_CommandResponse struct {
	CommandResponse *CommandResponse `protobuf:"bytes,3,opt,name=command_response,json=commandResponse,proto3,oneof"`
}

type Response_CommandStatusResponse struct {
	CommandStatusResponse *CommandStatusResponse `protobuf:"bytes,4,opt,name=command_status_response,json=commandStatusResponse,proto3,oneof"`
}

type Response_KeysResponse struct {
	KeysResponse *KeysResponse `protobuf:"bytes,5,opt,name=keys_response,json=keysResponse,proto3,oneof"`
}

type Response_FileResponse struct {
	FileResponse *FileResponse `protobuf:"bytes,6,opt,name=file_response,json=fileResponse,proto3,oneof"`
}

type Response_FileTransferStatusResponse struct {
	FileTransferStatusResponse *FileTransferStatusResponse `protobuf:"bytes,7,opt,name=file_transfer_status_response,json=fileTransferStatusResponse,proto3,oneof"`
}

func (*Response_ConfigurationResponse) isResponse_Payload() {}

func (*Response_CommandResponse) isResponse_Payload() {}

func (*Response_CommandStatusResponse) isResponse_Payload() {}

func (*Response_KeysResponse) isResponse_Payload() {}

func (*Response_FileResponse) isResponse_Payload() {}

func (*Response_FileTransferStatusResponse) isResponse_Payload() {}

type ConfigurationRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Uuid              string                 `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	Username          string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	Hostname          string                 `protobuf:"bytes,3,opt,name=hostname,proto3" json:"hostname,omitempty"`
	Ostype            string                 `protobuf:"bytes,4,opt,name=ostype,proto3" json:"ostype,omitempty"`
	Arch              string                 `protobuf:"bytes,5,opt,name=arch,proto3" json:"arch,omitempty"`
	Osbuild           string                 `protobuf:"bytes,6,opt,name=osbuild,proto3" json:"osbuild,omitempty"`
	Cpus              string                 `protobuf:"bytes,7,opt,name=cpus,proto3" json:"cpus,omitempty"`
	Memory            string                 `protobuf:"bytes,8,opt,name=memory,proto3" json:"memory,omitempty"`
	Agentip           string                 `protobuf:"bytes,9,opt,name=agentip,proto3" json:"agentip,omitempty"`
	Serverip          string                 `protobuf:"bytes,10,opt,name=serverip,proto3" json:"serverip,omitempty"`
	Serverport        string                 `protobuf:"bytes,11,opt,name=serverport,proto3" json:"serverport,omitempty"`
	Callbackfrequency string                 `protobuf:"bytes,12,opt,name=callbackfrequency,proto3" json:"callbackfrequency,omitempty"`
	Callbackjitter    string                 `protobuf:"bytes,13,opt,name=callbackjitter,proto3" json:"callbackjitter,omitempty"`
	Masterkey         string                 `protobuf:"bytes,14,opt,name=masterkey,proto3" json:"masterkey,omitempty"`
	Status            string                 `protobuf:"bytes,15,opt,name=status,proto3" json:"status,omitempty"`
	Tags              []*Tag                 `protobuf:"bytes,16,rep,name=tags,proto3" json:"tags,omitempty"`
	NextcallbackUnix  int64                  `protobuf:"varint,17,opt,name=nextcallback_unix,json=nextcallbackUnix,proto3" json:"nextcallback_unix,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ConfigurationRequest) Reset() {
	*x = ConfigurationRequest{}
	mi := &file_agents_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigurationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigurationRequest) ProtoMessage() {}

func (x *ConfigurationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agents_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigurationRequest.ProtoReflect.Descriptor instead.
func (*ConfigurationRequest) Descriptor() ([]byte, []int) {
	return file_agents_proto_rawDescGZIP(), []int{2}
}

func (x *ConfigurationRequest) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *ConfigurationRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *ConfigurationRequest) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *ConfigurationRequest) GetOstype() string {
	if x != nil {
		return x.Ostype
	}
	return ""
}

func (x *ConfigurationRequest) GetArch() string {
	if x != nil {
		return x.Arch
	}
	return ""
}

func (x *ConfigurationRequest) GetOsbuild() string {
	if x != nil {
		return x.Osbuild
	}
	return ""
}

func (x *ConfigurationRequest) GetCpus() string {
	if x != nil {
		return x.Cpus
	}
	return ""
}

func (x *ConfigurationRequest) GetMemory() string {
	if x != nil {
		return x.Memory
	}
	return ""
}

func (x *ConfigurationRequest) GetAgentip() string {
	if x != nil {
		return x.Agentip
	}
	return ""
}

func (x *ConfigurationRequest) GetServerip() string {
	if x != nil {
		return x.Serverip
	}
	return ""
}

func (x *ConfigurationRequest) GetServerport() string {
	if x != nil {
		return x.Serverport
	}
	return ""
}

func (x *ConfigurationRequest) GetCallbackfrequency() string {
	if x != nil {
		return x.Callbackfrequency
	}
	return ""
}

func (x *ConfigurationRequest) GetCallbackjitter() string {
	if x != nil {
		return x.Callbackjitter
	}
	return ""
}

func (x *ConfigurationRequest) GetMasterkey() string {
	if x != nil {
		return x.Masterkey
	}
	return ""
}

func (x *ConfigurationRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ConfigurationRequest) GetTags() []*Tag {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *ConfigurationRequest) GetNextcallbackUnix() int64 {
	if x != nil {
		return x.NextcallbackUnix
	}
	return 0
}

type ConfigurationResponse struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Uuid              string                 `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	Serverip          string                 `protobuf:"bytes,2,opt,name=serverip,proto3" json:"serverip,omitempty"`
	Serverport        string                 `protobuf:"bytes,3,opt,name=serverport,proto3" json:"serverport,omitempty"`
	Callbackfrequency string                 `protobuf:"bytes,4,opt,name=callbackfrequency,proto3" json:"callbackfrequency,omitempty"`
	Callbackjitter    string                 `protobuf:"bytes,5,opt,name=callbackjitter,proto3" json:"callbackjitter,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ConfigurationResponse) Reset() {
	*x = ConfigurationResponse{}
	mi := &file_agents_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigurationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigurationResponse) ProtoMessage() {}

func (x *ConfigurationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agents_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigurationResponse.ProtoReflect.Descriptor instead.
func (*ConfigurationResponse) Descriptor() ([]byte, []int) {
	return file_agents_proto_rawDescGZIP(), []int{3}
}

func (x *ConfigurationResponse) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *ConfigurationResponse) GetServerip() string {
	if x != nil {
		return x.Serverip
	}
	return ""
}

func (x *ConfigurationResponse) GetServerport() string {
	if x != nil {
		return x.Serverport
	}
	return ""
}

func (x *ConfigurationResponse) GetCallbackfrequency() string {
	if x != nil {
		return x.Callbackfrequency
	}
	return ""
}

func (x *ConfigurationResponse) GetCallbackjitter() string {
	if x != nil {
		return x.Callbackjitter
	}
	return ""
}

type CommandRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uuid          string                 `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommandRequest) Reset() {
	*x = CommandRequest{}
	mi := &file_agents_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommandRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommandRequest) ProtoMessage() {}

func (x *CommandRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agents_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommandRequest.ProtoReflect.Descriptor instead.
func (*CommandRequest) Descriptor() ([]byte, []int) {
	return file_agents_proto_rawDescGZIP(), []int{4}
}

func (x *CommandRequest) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

type CommandResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uuid          string                 `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	Commandtype   string                 `protobuf:"bytes,2,opt,name=commandtype,proto3" json:"commandtype,omitempty"`
	Commandid     string                 `protobuf:"bytes,3,opt,name=commandid,proto3" json:"commandid,omitempty"`
	Command       string                 `protobuf:"bytes,4,opt,name=command,proto3" json:"command,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommandResponse) Reset() {
	*x = CommandResponse{}
	mi := &file_agents_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommandResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommandResponse) ProtoMessage() {}

func (x *CommandResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agents_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommandResponse.ProtoReflect.Descriptor instead.
func (*CommandResponse) Descriptor() ([]byte, []int) {
	return file_agents_proto_rawDescGZIP(), []int{5}
}

func (x *CommandResponse) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *CommandResponse) GetCommandtype() string {
	if x != nil {
		return x.Commandtype
	}
	return ""
}

func (x *CommandResponse) GetCommandid() string {
	if x != nil {
		return x.Commandid
	}
	return ""
}

func (x *CommandResponse) GetCommand() string {
	if x != nil {
		return x.Command
	}
	return ""
}

type CommandStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uuid          string                 `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	Commandid     string                 `protobuf:"bytes,2,opt,name=commandid,proto3" json:"commandid,omitempty"`
	Result        string                 `protobuf:"bytes,3,opt,name=result,proto3" json:"result,omitempty"`
	Output        string                 `protobuf:"bytes,4,opt,name=output,proto3" json:"output,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommandStatusRequest) Reset() {
	*x = CommandStatusRequest{}
	mi := &file_agents_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommandStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommandStatusRequest) ProtoMessage() {}

func (x *CommandStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agents_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommandStatusRequest.ProtoReflect.Descriptor instead.
func (*CommandStatusRequest) Descriptor() ([]byte, []int) {
	return file_agents_proto_rawDescGZIP(), []int{6}
}

func (x *CommandStatusRequest) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *CommandStatusRequest) GetCommandid() string {
	if x != nil {
		return x.Commandid
	}
	return ""
}

func (x *CommandStatusRequest) GetResult() string {
	if x != nil {
		return x.Result
	}
	return ""
}

func (x *CommandStatusRequest) GetOutput() string {
	if x != nil {
		return x.Output
	}
	return ""
}

type CommandStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uuid          string                 `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommandStatusResponse) Reset() {
	*x = CommandStatusResponse{}
	mi := &file_agents_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommandStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommandStatusResponse) ProtoMessage() {}

func (x *CommandStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agents_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommandStatusResponse.ProtoReflect.Descriptor instead.
func (*CommandStatusResponse) Descriptor() ([]byte, []int) {
	return file_agents_proto_rawDescGZIP(), []int{7}
}

func (x *CommandStatusResponse) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

type KeysRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uuid          string                 `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	Keys          string                 `protobuf:"bytes,2,opt,name=keys,proto3" json:"keys,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KeysRequest) Reset() {
	*x = KeysRequest{}
	mi := &file_agents_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KeysRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KeysRequest) ProtoMessage() {}

func (x *KeysRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agents_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KeysRequest.ProtoReflect.Descriptor instead.
func (*KeysRequest) Descriptor() ([]byte, []int) {
	return file_agents_proto_rawDescGZIP(), []int{8}
}

func (x *KeysRequest) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *KeysRequest) GetKeys() string {
	if x != nil {
		return x.Keys
	}
	return ""
}

type KeysResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uuid          string                 `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KeysResponse) Reset() {
	*x = KeysResponse{}
	mi := &file_agents_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KeysResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KeysResponse) ProtoMessage() {}

func (x *KeysResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agents_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KeysResponse.ProtoReflect.Descriptor instead.
func (*KeysResponse) Descriptor() ([]byte, []int) {
	return file_agents_proto_rawDescGZIP(), []int{9}
}

func (x *KeysResponse) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

type FileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uuid          string                 `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileRequest) Reset() {
	*x = FileRequest{}
	mi := &file_agents_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileRequest) ProtoMessage() {}

func (x *FileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agents_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileRequest.ProtoReflect.Descriptor instead.
func (*FileRequest) Descriptor() ([]byte, []int) {
	return file_agents_proto_rawDescGZIP(), []int{10}
}

func (x *FileRequest) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

type FileResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Fileid        string                 `protobuf:"bytes,1,opt,name=fileid,proto3" json:"fileid,omitempty"`
	Uuid          string                 `protobuf:"bytes,2,opt,name=uuid,proto3" json:"uuid,omitempty"`
	Transfertype  string                 `protobuf:"bytes,3,opt,name=transfertype,proto3" json:"transfertype,omitempty"`
	Filepath      string                 `protobuf:"bytes,4,opt,name=filepath,proto3" json:"filepath,omitempty"`
	Chunk         []byte                 `protobuf:"bytes,5,opt,name=chunk,proto3" json:"chunk,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileResponse) Reset() {
	*x = FileResponse{}
	mi := &file_agents_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileResponse) ProtoMessage() {}

func (x *FileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agents_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileResponse.ProtoReflect.Descriptor instead.
func (*FileResponse) Descriptor() ([]byte, []int) {
	return file_agents_proto_rawDescGZIP(), []int{11}
}

func (x *FileResponse) GetFileid() string {
	if x != nil {
		return x.Fileid
	}
	return ""
}

func (x *FileResponse) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *FileResponse) GetTransfertype() string {
	if x != nil {
		return x.Transfertype
	}
	return ""
}

func (x *FileResponse) GetFilepath() string {
	if x != nil {
		return x.Filepath
	}
	return ""
}

func (x *FileResponse) GetChunk() []byte {
	if x != nil {
		return x.Chunk
	}
	return nil
}

type FileToServer struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Fileid        string                 `protobuf:"bytes,1,opt,name=fileid,proto3" json:"fileid,omitempty"`
	Uuid          string                 `protobuf:"bytes,2,opt,name=uuid,proto3" json:"uuid,omitempty"`
	Transfertype  string                 `protobuf:"bytes,3,opt,name=transfertype,proto3" json:"transfertype,omitempty"`
	Path          string                 `protobuf:"bytes,4,opt,name=path,proto3" json:"path,omitempty"`
	Status        string                 `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`
	Chunk         []byte                 `protobuf:"bytes,6,opt,name=chunk,proto3" json:"chunk,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileToServer) Reset() {
	*x = FileToServer{}
	mi := &file_agents_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileToServer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileToServer) ProtoMessage() {}

func (x *FileToServer) ProtoReflect() protoreflect.Message {
	mi := &file_agents_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileToServer.ProtoReflect.Descriptor instead.
func (*FileToServer) Descriptor() ([]byte, []int) {
	return file_agents_proto_rawDescGZIP(), []int{12}
}

func (x *FileToServer) GetFileid() string {
	if x != nil {
		return x.Fileid
	}
	return ""
}

func (x *FileToServer) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *FileToServer) GetTransfertype() string {
	if x != nil {
		return x.Transfertype
	}
	return ""
}

func (x *FileToServer) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *FileToServer) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *FileToServer) GetChunk() []byte {
	if x != nil {
		return x.Chunk
	}
	return nil
}

type FileTransferStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Fileid        string                 `protobuf:"bytes,1,opt,name=fileid,proto3" json:"fileid,omitempty"`
	Uuid          string                 `protobuf:"bytes,2,opt,name=uuid,proto3" json:"uuid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileTransferStatusResponse) Reset() {
	*x = FileTransferStatusResponse{}
	mi := &file_agents_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileTransferStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileTransferStatusResponse) ProtoMessage() {}

func (x *FileTransferStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agents_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileTransferStatusResponse.ProtoReflect.Descriptor instead.
func (*FileTransferStatusResponse) Descriptor() ([]byte, []int) {
	return file_agents_proto_rawDescGZIP(), []int{13}
}

func (x *FileTransferStatusResponse) GetFileid() string {
	if x != nil {
		return x.Fileid
	}
	return ""
}

func (x *FileTransferStatusResponse) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

type Tag struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value         string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Tag) Reset() {
	*x = Tag{}
	mi := &file_agents_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Tag) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Tag) ProtoMessage() {}

func (x *Tag) ProtoReflect() protoreflect.Message {
	mi := &file_agents_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Tag.ProtoReflect.Descriptor instead.
func (*Tag) Descriptor() ([]byte, []int) {
	return file_agents_proto_rawDescGZIP(), []int{14}
}

func (x *Tag) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *Tag) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

var File_agents_proto protoreflect.FileDescriptor

const file_agents_proto_rawDesc = "" +
	"\n" +
	"\fagents.proto\x12\n" +
	"patronobuf\"\xae\x03\n" +
	"\aRequest\x12+\n" +
	"\x04type\x18\x01 \x01(\x0e2\x17.patronobuf.RequestTypeR\x04type\x12H\n" +
	"\rconfiguration\x18\x02 \x01(\v2 .patronobuf.ConfigurationRequestH\x00R\rconfiguration\x126\n" +
	"\acommand\x18\x03 \x01(\v2\x1a.patronobuf.CommandRequestH\x00R\acommand\x12I\n" +
	"\x0ecommand_status\x18\x04 \x01(\v2 .patronobuf.CommandStatusRequestH\x00R\rcommandStatus\x12-\n" +
	"\x04keys\x18\x05 \x01(\v2\x17.patronobuf.KeysRequestH\x00R\x04keys\x12-\n" +
	"\x04file\x18\x06 \x01(\v2\x17.patronobuf.FileRequestH\x00R\x04file\x12@\n" +
	"\x0efile_to_server\x18\a \x01(\v2\x18.patronobuf.FileToServerH\x00R\ffileToServerB\t\n" +
	"\apayload\"\xb5\x04\n" +
	"\bResponse\x12,\n" +
	"\x04type\x18\x01 \x01(\x0e2\x18.patronobuf.ResponseTypeR\x04type\x12Z\n" +
	"\x16configuration_response\x18\x02 \x01(\v2!.patronobuf.ConfigurationResponseH\x00R\x15configurationResponse\x12H\n" +
	"\x10command_response\x18\x03 \x01(\v2\x1b.patronobuf.CommandResponseH\x00R\x0fcommandResponse\x12[\n" +
	"\x17command_status_response\x18\x04 \x01(\v2!.patronobuf.CommandStatusResponseH\x00R\x15commandStatusResponse\x12?\n" +
	"\rkeys_response\x18\x05 \x01(\v2\x18.patronobuf.KeysResponseH\x00R\fkeysResponse\x12?\n" +
	"\rfile_response\x18\x06 \x01(\v2\x18.patronobuf.FileResponseH\x00R\ffileResponse\x12k\n" +
	"\x1dfile_transfer_status_response\x18\a \x01(\v2&.patronobuf.FileTransferStatusResponseH\x00R\x1afileTransferStatusResponseB\t\n" +
	"\apayload\"\x88\x04\n" +
	"\x14ConfigurationRequest\x12\x12\n" +
	"\x04uuid\x18\x01 \x01(\tR\x04uuid\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\x12\x1a\n" +
	"\bhostname\x18\x03 \x01(\tR\bhostname\x12\x16\n" +
	"\x06ostype\x18\x04 \x01(\tR\x06ostype\x12\x12\n" +
	"\x04arch\x18\x05 \x01(\tR\x04arch\x12\x18\n" +
	"\aosbuild\x18\x06 \x01(\tR\aosbuild\x12\x12\n" +
	"\x04cpus\x18\a \x01(\tR\x04cpus\x12\x16\n" +
	"\x06memory\x18\b \x01(\tR\x06memory\x12\x18\n" +
	"\aagentip\x18\t \x01(\tR\aagentip\x12\x1a\n" +
	"\bserverip\x18\n" +
	" \x01(\tR\bserverip\x12\x1e\n" +
	"\n" +
	"serverport\x18\v \x01(\tR\n" +
	"serverport\x12,\n" +
	"\x11callbackfrequency\x18\f \x01(\tR\x11callbackfrequency\x12&\n" +
	"\x0ecallbackjitter\x18\r \x01(\tR\x0ecallbackjitter\x12\x1c\n" +
	"\tmasterkey\x18\x0e \x01(\tR\tmasterkey\x12\x16\n" +
	"\x06status\x18\x0f \x01(\tR\x06status\x12#\n" +
	"\x04tags\x18\x10 \x03(\v2\x0f.patronobuf.TagR\x04tags\x12+\n" +
	"\x11nextcallback_unix\x18\x11 \x01(\x03R\x10nextcallbackUnix\"\xbd\x01\n" +
	"\x15ConfigurationResponse\x12\x12\n" +
	"\x04uuid\x18\x01 \x01(\tR\x04uuid\x12\x1a\n" +
	"\bserverip\x18\x02 \x01(\tR\bserverip\x12\x1e\n" +
	"\n" +
	"serverport\x18\x03 \x01(\tR\n" +
	"serverport\x12,\n" +
	"\x11callbackfrequency\x18\x04 \x01(\tR\x11callbackfrequency\x12&\n" +
	"\x0ecallbackjitter\x18\x05 \x01(\tR\x0ecallbackjitter\"$\n" +
	"\x0eCommandRequest\x12\x12\n" +
	"\x04uuid\x18\x01 \x01(\tR\x04uuid\"\x7f\n" +
	"\x0fCommandResponse\x12\x12\n" +
	"\x04uuid\x18\x01 \x01(\tR\x04uuid\x12 \n" +
	"\vcommandtype\x18\x02 \x01(\tR\vcommandtype\x12\x1c\n" +
	"\tcommandid\x18\x03 \x01(\tR\tcommandid\x12\x18\n" +
	"\acommand\x18\x04 \x01(\tR\acommand\"x\n" +
	"\x14CommandStatusRequest\x12\x12\n" +
	"\x04uuid\x18\x01 \x01(\tR\x04uuid\x12\x1c\n" +
	"\tcommandid\x18\x02 \x01(\tR\tcommandid\x12\x16\n" +
	"\x06result\x18\x03 \x01(\tR\x06result\x12\x16\n" +
	"\x06output\x18\x04 \x01(\tR\x06output\"+\n" +
	"\x15CommandStatusResponse\x12\x12\n" +
	"\x04uuid\x18\x01 \x01(\tR\x04uuid\"5\n" +
	"\vKeysRequest\x12\x12\n" +
	"\x04uuid\x18\x01 \x01(\tR\x04uuid\x12\x12\n" +
	"\x04keys\x18\x02 \x01(\tR\x04keys\"\"\n" +
	"\fKeysResponse\x12\x12\n" +
	"\x04uuid\x18\x01 \x01(\tR\x04uuid\"!\n" +
	"\vFileRequest\x12\x12\n" +
	"\x04uuid\x18\x01 \x01(\tR\x04uuid\"\x90\x01\n" +
	"\fFileResponse\x12\x16\n" +
	"\x06fileid\x18\x01 \x01(\tR\x06fileid\x12\x12\n" +
	"\x04uuid\x18\x02 \x01(\tR\x04uuid\x12\"\n" +
	"\ftransfertype\x18\x03 \x01(\tR\ftransfertype\x12\x1a\n" +
	"\bfilepath\x18\x04 \x01(\tR\bfilepath\x12\x14\n" +
	"\x05chunk\x18\x05 \x01(\fR\x05chunk\"\xa0\x01\n" +
	"\fFileToServer\x12\x16\n" +
	"\x06fileid\x18\x01 \x01(\tR\x06fileid\x12\x12\n" +
	"\x04uuid\x18\x02 \x01(\tR\x04uuid\x12\"\n" +
	"\ftransfertype\x18\x03 \x01(\tR\ftransfertype\x12\x12\n" +
	"\x04path\x18\x04 \x01(\tR\x04path\x12\x16\n" +
	"\x06status\x18\x05 \x01(\tR\x06status\x12\x14\n" +
	"\x05chunk\x18\x06 \x01(\fR\x05chunk\"H\n" +
	"\x1aFileTransferStatusResponse\x12\x16\n" +
	"\x06fileid\x18\x01 \x01(\tR\x06fileid\x12\x12\n" +
	"\x04uuid\x18\x02 \x01(\tR\x04uuid\"-\n" +
	"\x03Tag\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value*i\n" +
	"\vRequestType\x12\x11\n" +
	"\rCONFIGURATION\x10\x00\x12\v\n" +
	"\aCOMMAND\x10\x01\x12\x12\n" +
	"\x0eCOMMAND_STATUS\x10\x02\x12\b\n" +
	"\x04KEYS\x10\x03\x12\b\n" +
	"\x04FILE\x10\x04\x12\x12\n" +
	"\x0eFILE_TO_SERVER\x10\x05*\x9d\x01\n" +
	"\fResponseType\x12\x1a\n" +
	"\x16CONFIGURATION_RESPONSE\x10\x00\x12\x14\n" +
	"\x10COMMAND_RESPONSE\x10\x01\x12\x1b\n" +
	"\x17COMMAND_STATUS_RESPONSE\x10\x02\x12\x11\n" +
	"\rKEYS_RESPONSE\x10\x03\x12\x11\n" +
	"\rFILE_RESPONSE\x10\x04\x12\x18\n" +
	"\x14FILE_TRANSFER_STATUS\x10\x05B.Z,github.com/PatronC2/Patronobuf/go/patronobufb\x06proto3"

var (
	file_agents_proto_rawDescOnce sync.Once
	file_agents_proto_rawDescData []byte
)

func file_agents_proto_rawDescGZIP() []byte {
	file_agents_proto_rawDescOnce.Do(func() {
		file_agents_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_agents_proto_rawDesc), len(file_agents_proto_rawDesc)))
	})
	return file_agents_proto_rawDescData
}

var file_agents_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_agents_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_agents_proto_goTypes = []any{
	(RequestType)(0),                   // 0: patronobuf.RequestType
	(ResponseType)(0),                  // 1: patronobuf.ResponseType
	(*Request)(nil),                    // 2: patronobuf.Request
	(*Response)(nil),                   // 3: patronobuf.Response
	(*ConfigurationRequest)(nil),       // 4: patronobuf.ConfigurationRequest
	(*ConfigurationResponse)(nil),      // 5: patronobuf.ConfigurationResponse
	(*CommandRequest)(nil),             // 6: patronobuf.CommandRequest
	(*CommandResponse)(nil),            // 7: patronobuf.CommandResponse
	(*CommandStatusRequest)(nil),       // 8: patronobuf.CommandStatusRequest
	(*CommandStatusResponse)(nil),      // 9: patronobuf.CommandStatusResponse
	(*KeysRequest)(nil),                // 10: patronobuf.KeysRequest
	(*KeysResponse)(nil),               // 11: patronobuf.KeysResponse
	(*FileRequest)(nil),                // 12: patronobuf.FileRequest
	(*FileResponse)(nil),               // 13: patronobuf.FileResponse
	(*FileToServer)(nil),               // 14: patronobuf.FileToServer
	(*FileTransferStatusResponse)(nil), // 15: patronobuf.FileTransferStatusResponse
	(*Tag)(nil),                        // 16: patronobuf.Tag
}
var file_agents_proto_depIdxs = []int32{
	0,  // 0: patronobuf.Request.type:type_name -> patronobuf.RequestType
	4,  // 1: patronobuf.Request.configuration:type_name -> patronobuf.ConfigurationRequest
	6,  // 2: patronobuf.Request.command:type_name -> patronobuf.CommandRequest
	8,  // 3: patronobuf.Request.command_status:type_name -> patronobuf.CommandStatusRequest
	10, // 4: patronobuf.Request.keys:type_name -> patronobuf.KeysRequest
	12, // 5: patronobuf.Request.file:type_name -> patronobuf.FileRequest
	14, // 6: patronobuf.Request.file_to_server:type_name -> patronobuf.FileToServer
	1,  // 7: patronobuf.Response.type:type_name -> patronobuf.ResponseType
	5,  // 8: patronobuf.Response.configuration_response:type_name -> patronobuf.ConfigurationResponse
	7,  // 9: patronobuf.Response.command_response:type_name -> patronobuf.CommandResponse
	9,  // 10: patronobuf.Response.command_status_response:type_name -> patronobuf.CommandStatusResponse
	11, // 11: patronobuf.Response.keys_response:type_name -> patronobuf.KeysResponse
	13, // 12: patronobuf.Response.file_response:type_name -> patronobuf.FileResponse
	15, // 13: patronobuf.Response.file_transfer_status_response:type_name -> patronobuf.FileTransferStatusResponse
	16, // 14: patronobuf.ConfigurationRequest.tags:type_name -> patronobuf.Tag
	15, // [15:15] is the sub-list for method output_type
	15, // [15:15] is the sub-list for method input_type
	15, // [15:15] is the sub-list for extension type_name
	15, // [15:15] is the sub-list for extension extendee
	0,  // [0:15] is the sub-list for field type_name
}

func init() { file_agents_proto_init() }
func file_agents_proto_init() {
	if File_agents_proto != nil {
		return
	}
	file_agents_proto_msgTypes[0].OneofWrappers = []any{
		(*Request_Configuration)(nil),
		(*Request_Command)(nil),
		(*Request_CommandStatus)(nil),
		(*Request_Keys)(nil),
		(*Request_File)(nil),
		(*Request_FileToServer)(nil),
	}
	file_agents_proto_msgTypes[1].OneofWrappers = []any{
		(*Response_ConfigurationResponse)(nil),
		(*Response_CommandResponse)(nil),
		(*Response_CommandStatusResponse)(nil),
		(*Response_KeysResponse)(nil),
		(*Response_FileResponse)(nil),
		(*Response_FileTransferStatusResponse)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_agents_proto_rawDesc), len(file_agents_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_agents_proto_goTypes,
		DependencyIndexes: file_agents_proto_depIdxs,
		EnumInfos:         file_agents_proto_enumTypes,
		MessageInfos:      file_agents_proto_msgTypes,
	}.Build()
	File_agents_proto = out.File
	file_agents_proto_goTypes = nil
	file_agents_proto_depIdxs = nil
}
