# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: agents.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("agents.proto", :syntax => :proto3) do
    add_message "patronobuf.Request" do
      optional :type, :enum, 1, "patronobuf.RequestType"
      oneof :payload do
        optional :startup, :message, 2, "patronobuf.StartupRequest"
        optional :configuration, :message, 3, "patronobuf.ConfigurationRequest"
        optional :command, :message, 4, "patronobuf.CommandRequest"
        optional :command_status, :message, 5, "patronobuf.CommandStatusRequest"
        optional :keys, :message, 6, "patronobuf.KeysRequest"
        optional :file, :message, 7, "patronobuf.FileRequest"
        optional :file_to_server, :message, 8, "patronobuf.FileToServer"
      end
    end
    add_message "patronobuf.Response" do
      optional :type, :enum, 1, "patronobuf.ResponseType"
      oneof :payload do
        optional :startup_response, :message, 2, "patronobuf.StartupResponse"
        optional :configuration_response, :message, 3, "patronobuf.ConfigurationResponse"
        optional :command_response, :message, 4, "patronobuf.CommandResponse"
        optional :command_status_response, :message, 5, "patronobuf.CommandStatusResponse"
        optional :keys_response, :message, 6, "patronobuf.KeysResponse"
        optional :file_response, :message, 7, "patronobuf.FileResponse"
        optional :file_transfer_status_response, :message, 8, "patronobuf.FileTransferStatusResponse"
      end
    end
    add_message "patronobuf.StartupRequest" do
      optional :filepath, :string, 1
      optional :username, :string, 2
      optional :hostname, :string, 3
      optional :ostype, :string, 4
      optional :arch, :string, 5
      optional :osbuild, :string, 6
      optional :cpus, :string, 7
      optional :memory, :string, 8
      optional :agentip, :string, 9
      repeated :capabilities, :string, 10
    end
    add_message "patronobuf.StartupResponse" do
      optional :uuid, :string, 1
    end
    add_message "patronobuf.ConfigurationRequest" do
      optional :uuid, :string, 1
      optional :serverip, :string, 2
      optional :serverport, :string, 3
      optional :callbackfrequency, :string, 4
      optional :callbackjitter, :string, 5
      optional :masterkey, :string, 6
      optional :status, :string, 7
      repeated :tags, :message, 8, "patronobuf.Tag"
      optional :nextcallback_unix, :int64, 9
      optional :transportprotocol, :string, 10
    end
    add_message "patronobuf.ConfigurationResponse" do
      optional :serverip, :string, 2
      optional :serverport, :string, 3
      optional :transportprotocol, :string, 6
      optional :sleep_seconds, :int64, 7
    end
    add_message "patronobuf.CommandRequest" do
      optional :uuid, :string, 1
    end
    add_message "patronobuf.CommandResponse" do
      optional :uuid, :string, 1
      optional :commandtype, :string, 2
      optional :commandid, :string, 3
      optional :command, :string, 4
    end
    add_message "patronobuf.CommandStatusRequest" do
      optional :uuid, :string, 1
      optional :commandid, :string, 2
      optional :result, :string, 3
      optional :output, :string, 4
    end
    add_message "patronobuf.CommandStatusResponse" do
      optional :uuid, :string, 1
    end
    add_message "patronobuf.KeysRequest" do
      optional :uuid, :string, 1
      optional :keys, :string, 2
    end
    add_message "patronobuf.KeysResponse" do
      optional :uuid, :string, 1
    end
    add_message "patronobuf.FileRequest" do
      optional :uuid, :string, 1
    end
    add_message "patronobuf.FileResponse" do
      optional :fileid, :string, 1
      optional :uuid, :string, 2
      optional :transfertype, :string, 3
      optional :filepath, :string, 4
      optional :chunk, :bytes, 5
    end
    add_message "patronobuf.FileToServer" do
      optional :fileid, :string, 1
      optional :uuid, :string, 2
      optional :transfertype, :string, 3
      optional :path, :string, 4
      optional :status, :string, 5
      optional :chunk, :bytes, 6
    end
    add_message "patronobuf.FileTransferStatusResponse" do
      optional :fileid, :string, 1
      optional :uuid, :string, 2
    end
    add_message "patronobuf.Tag" do
      optional :key, :string, 1
      optional :value, :string, 2
    end
    add_enum "patronobuf.RequestType" do
      value :STARTUP, 0
      value :CONFIGURATION, 1
      value :COMMAND, 2
      value :COMMAND_STATUS, 3
      value :KEYS, 4
      value :FILE, 5
      value :FILE_TO_SERVER, 6
    end
    add_enum "patronobuf.ResponseType" do
      value :STARTUP_RESPONSE, 0
      value :CONFIGURATION_RESPONSE, 1
      value :COMMAND_RESPONSE, 2
      value :COMMAND_STATUS_RESPONSE, 3
      value :KEYS_RESPONSE, 4
      value :FILE_RESPONSE, 5
      value :FILE_TRANSFER_STATUS, 6
    end
  end
end

module Patronobuf
  Request = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("patronobuf.Request").msgclass
  Response = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("patronobuf.Response").msgclass
  StartupRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("patronobuf.StartupRequest").msgclass
  StartupResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("patronobuf.StartupResponse").msgclass
  ConfigurationRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("patronobuf.ConfigurationRequest").msgclass
  ConfigurationResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("patronobuf.ConfigurationResponse").msgclass
  CommandRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("patronobuf.CommandRequest").msgclass
  CommandResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("patronobuf.CommandResponse").msgclass
  CommandStatusRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("patronobuf.CommandStatusRequest").msgclass
  CommandStatusResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("patronobuf.CommandStatusResponse").msgclass
  KeysRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("patronobuf.KeysRequest").msgclass
  KeysResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("patronobuf.KeysResponse").msgclass
  FileRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("patronobuf.FileRequest").msgclass
  FileResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("patronobuf.FileResponse").msgclass
  FileToServer = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("patronobuf.FileToServer").msgclass
  FileTransferStatusResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("patronobuf.FileTransferStatusResponse").msgclass
  Tag = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("patronobuf.Tag").msgclass
  RequestType = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("patronobuf.RequestType").enummodule
  ResponseType = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("patronobuf.ResponseType").enummodule
end
